using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public enum AntigenType
{
    staph = 0,  //é”Ÿæ–¤æ‹·é”Ÿç¼??é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿ?
    Strep = 1,    //é“¾çƒèŒç—…åŸä½“
    Virus = 2
}
public class StemCell : MonoBehaviour
{
    public Position p;
    public Vector3 target;
    public float speed;     //é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿç‹¡è®¹æ‹·é”ŸåŠ«è®¹æ‹?
    public bool isMove = false;
    public int forward_step = 0;



    public Dictionary<AntigenType, byte> antigens = new Dictionary<AntigenType, byte>(); //é”Ÿæ–¤æ‹·åŸé”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿé…µçŒ´æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·
    public byte ATP;         //é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·
    public byte ATPMax;      //é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·
    public byte ATPspeed;   //é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæˆªé©æ‹·é”ŸåŠ«è®¹æ‹·
    public int ATPbuffRound;//é€„¤ç°¬atpgeté—ï¼„å¢?
    public byte extraReward;
    public int rewardRound;


    protected virtual void Awake()
    {
        speed = 3f;
        ATPbuffRound = 0;

        //ä¸ºé”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·ç§ƒé”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿè¡—?
        antigens.Add(AntigenType.staph, 2);//2é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·é”Ÿæ–¤æ‹·ä¸ºé”Ÿå‰¿è¯§æ‹·é”Ÿçš†ï½æ‹·å®é”Ÿæ–¤æ‹·åº”é”Ÿæ–¤æ‹·ä¸?0
        antigens.Add(AntigenType.Strep, 2);
        antigens.Add(AntigenType.Virus,2);
    }

    public virtual void TurnStart ()
    {
        ATPrecover();
        
    }

    protected virtual void ATPrecover()
    {
        byte addUp=ATPspeed;
        if(ATPbuffRound>0){
            addUp  += 1;
            ATPbuffRound-=1; 
        }
        if (ATP < ATPMax)
        {
            ATP += addUp;
        }
        if(rewardRound>0){
            rewardRound--;
            if(rewardRound == 0){
                ATP+=extraReward;
            }
        }
        if(Board.instance.immuneBuffRound>0){
            ATP+=1;
        }
        if(ATP > ATPMax)
        {
            ATP = ATPMax;
        }
    }

    protected void Update()
    {
        if (isMove)
        {
            transform.position = Vector3.MoveTowards(transform.position, target, speed * Time.deltaTime);
        }
        if (target!=null)
        {
            if (transform.position == target)
            {
                isMove = false;
                
            }
        }            
    }
}
